services:
  backend:
    build: .
    ports:
      - "8686:8686"
    volumes:
      - ouroboros-volume:/ouroboros-volume
    environment:
      - VOLUME_MOUNT_PATH=/ouroboros-volume
      - VOLUME_SERVER_URL=http://host.docker.internal:3001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ouroboros-volume:
    external: true
