services:
  backend:
    build: .
    ports:
      - "8686:8686"
    volumes:
      - ouroboros-volume:/ouroboros-volume
    environment:
      - VOLUME_MOUNT_PATH=/ouroboros-volume
      - VOLUME_SERVER_URL=http://host.docker.internal:3001
      # Frame loading mode: "sync" (safer, slower) or "async" (faster, may have threading issues)
      - SAM2_FRAME_LOADING_MODE=async
    shm_size: 1gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ouroboros-volume:
    external: true
